#!/usr/bin/env python3
import os
import argparse
from pathlib import Path
import re

def read_card(path):
    content = path.read_text()
    # Simple frontmatter parsing
    parts = content.split("---")
    metadata = {}
    body = content
    if len(parts) >= 3:
        for line in parts[1].splitlines():
            if ":" in line:
                k, v = line.split(":", 1)
                metadata[k.strip()] = v.strip()
        body = "---".join(parts[2:]).strip()
    return metadata, body

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--cards-dir", required=True)
    parser.add_argument("--output-dir", required=True)
    args = parser.parse_args()

    cards_dir = Path(args.cards_dir)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    concepts, workflows, decisions, traps, signatures = [], [], [], [], []
    
    for root, _, files in os.walk(cards_dir):
        for f in files:
            if f.endswith(".md"):
                path = Path(root) / f
                meta, body = read_card(path)
                ctype = meta.get("type", "")
                if ctype == "concept": concepts.append((meta, body))
                elif ctype == "workflow": workflows.append((meta, body))
                elif ctype == "decision": decisions.append((meta, body))
                elif ctype == "trap": traps.append((meta, body))
                elif ctype == "signature": signatures.append((meta, body))

    # Compile SKILL.md
    skill_content = """---
name: wifi-password-manager-pro
description: An advanced WiFi password manager generated by Doramagic.
version: 1.0.0
user-invocable: true
allowed-tools: [exec, read, write]
---

# WiFi Password Manager Pro Skill

This skill allows you to manage, backup, and share WiFi passwords securely.

## WHY (Core Design Philosophies)
"""
    for meta, body in decisions:
        skill_content += f"\n### {meta.get('title', 'Decision')}\n{body}\n"

    skill_content += "\n## UNSAID (Traps and Community Wisdom)\n"
    for meta, body in traps:
        skill_content += f"\n### {meta.get('title', 'Trap')}\n{body}\n"
    
    skill_content += "\n## Concepts\n"
    for meta, body in concepts:
        skill_content += f"\n### {meta.get('title', 'Concept')}\n{body}\n"

    (output_dir / "SKILL.md").write_text(skill_content)

    # Compile PROVENANCE.md
    prov_content = "# PROVENANCE.md\n\n## Sources\n"
    prov_content += "- https://github.com/Khh-vu/wifi-password-manager\n"
    prov_content += "- https://github.com/muelli/network-manager-qrcode\n\n"
    prov_content += "## Knowledge Traceability\n"
    
    for meta, body in decisions + traps + concepts:
        prov_content += f"- Card ID: {meta.get('id', 'N/A')} - {meta.get('title', 'N/A')}\n"
        if meta.get("type") == "decision":
            prov_content += "  - WHY Evidence Sufficient: Direct from issues/consensus.\n"

    (output_dir / "PROVENANCE.md").write_text(prov_content)

    # Compile LIMITATIONS.md
    lim_content = """# LIMITATIONS.md

## Dark Trap Evaluation
- **Risk Level**: Low to Medium
- **Findings**:
  - *Exception Bias*: Minor. Some issues focus on edge cases like specific password lengths, but core functionality is solid.
  - *Over-engineering*: None detected. Implementations are straightforward.
  - *Deceptive Patterns*: None. The code aligns with the documentation.

## Functional Limitations
- Shizuku is required on unrooted devices, which requires user technical knowledge to setup via ADB.
- QR Code generation currently does not support WEP/WPA3 specifically, defaulting to generic WPA format.
"""
    (output_dir / "LIMITATIONS.md").write_text(lim_content)

    print(f"Skill bundle assembled in {output_dir}")

if __name__ == "__main__":
    main()
