"""Routing contracts for v12.1.1 Input Router.

Deterministic routing decisions -- no LLM involved.
"""

from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel, Field


class RoutingDecision(BaseModel):
    """Deterministic routing decision generated by InputRouter.

    Route kinds:
      DIRECT_URL     -- user gave explicit repo URL(s), skip Discovery
      NAMED_PROJECT  -- user named a project, targeted Discovery
      DOMAIN_EXPLORE -- user described a domain, broad Discovery
      LOW_CONFIDENCE -- ambiguous input, need clarification
    """

    schema_version: str = "dm.routing-decision.v1"
    route: Literal["DIRECT_URL", "NAMED_PROJECT", "DOMAIN_EXPLORE", "LOW_CONFIDENCE"]
    skip_discovery: bool = False
    max_repos: int = Field(default=3, ge=1, le=5)
    repo_urls: list[str] = []
    project_names: list[str] = []
    confidence: float = Field(default=0.5, ge=0.0, le=1.0)
    reasoning: str = ""


class NeedProfileContract(BaseModel):
    """Extended Phase A output: NeedProfile + routing decision.

    This is what Phase A passes downstream -- solving information hunger.
    """

    schema_version: str = "dm.need-profile-contract.v1"
    raw_input: str
    keywords: list[str] = []
    intent: str = ""
    intent_en: Optional[str] = None
    domain: str = "general"
    search_directions: list[dict] = []
    constraints: list[str] = []
    github_queries: list[str] = []
    relevance_terms: list[str] = []
    confidence: float = 0.5
    routing: RoutingDecision
    clarification_questions: list[str] = []


class DeliveryTier(BaseModel):
    """Delivery completeness tier for degraded delivery."""

    schema_version: str = "dm.delivery-tier.v1"
    tier: Literal["FULL", "PARTIAL_SOULS", "FAST_PATH", "TEMPLATE", "SEARCH_ONLY", "EMPTY"]
    completeness_pct: int = Field(ge=0, le=100)
    degraded_at_phase: Optional[str] = None
    degradation_reason: str = ""
    suggestions: list[str] = []
    user_message: str = ""


class DeliveryManifest(BaseModel):
    """Final delivery output from Phase G."""

    schema_version: str = "dm.delivery-manifest.v1"
    delivery_tier: DeliveryTier
    artifact_paths: dict[str, str] = {}
    run_summary: dict = {}
    user_message: str = ""
